name: Test and publish

on: [push]

jobs:
  lint:
    name: Run flake8 linter
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        name: Set up Python 3.7
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install tox
      - name: Lint
        run: tox -e flake8

  test:
    name: Run tests
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        name: Set up Python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install tox
      - name: Test
        run: tox -e py
      - name: Upload coverage results
        if: ${{ matrix.python-version == '3.7' }}
        run: pip install codacy-coverage && python-codacy-coverage -r coverage.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

  publish:
   name: Publish package
   runs-on: ubuntu-18.04
   needs: [lint, test]
   steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        name: Set up Python 3.7
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install pep517 --user
      - name: Build
        run: python -m pep517.build --source --binary --out-dir dist/ .
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.3.1
        if: startsWith(github.ref, 'refs/tags')
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
#          password: ${{ secrets.TEST_PYPI_PASSWORD }}
#          repository_url: https://test.pypi.org/legacy/
